# Generated by Django 6.1 on 2026-08-30 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DandiyaEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('venue', models.CharField(max_length=255)),
                ('registration_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Fee per person. Leave blank until the fee is decided.', max_digits=10, null=True)),
                ('group_discount_percent', models.DecimalField(decimal_places=2, default=0, help_text='Group discount percentage. Keep 0 until decided.', max_digits=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to='dandiya/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='DandiyaRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('number_of_participants', models.PositiveIntegerField(default=1)),
                ('registration_type', models.CharField(choices=[('Individual', 'Individual'), ('Group', 'Group')], default='Individual', max_length=20)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('payment_id', models.CharField(blank=True, max_length=255)),
                ('entry_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='core.dandiyaevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
