# Generated by Django 6.1 on 2026-08-31 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dandiyaevent_dandiyaregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dandiyaevent',
            name='registration_fee',
        ),
        migrations.RemoveField(
            model_name='dandiyaregistration',
            name='registration_type',
        ),
        migrations.AlterField(
            model_name='dandiyaevent',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DandiyaPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_people', models.PositiveIntegerField(default=1, help_text='Number of people covered by this pass.')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='core.dandiyaevent')),
            ],
            options={
                'ordering': ['display_order', 'price'],
            },
        ),
        migrations.AddField(
            model_name='dandiyaregistration',
            name='dandiya_pass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='core.dandiyapass'),
        ),
        migrations.CreateModel(
            name='DandiyaSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='dandiya/sponsors/')),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='core.dandiyaevent')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
