# Generated by Django 6.1 on 2026-09-07 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_schedule_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dandiyaregistration',
            old_name='number_of_participants',
            new_name='number_of_passes',
        ),
    ]
