# Generated by Django 6.1 on 2026-09-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_number_of_participants_dandiyaregistration_number_of_passes'),
    ]

    operations = [
        migrations.AddField(
            model_name='dandiyaregistration',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dandiyaregistration',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
