# Generated by Django 6.1 on 2026-09-10 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_dandiyaregistration_checked_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dandiyaregistration',
            name='coupon_token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
